; SPDX-License-Identifier: GPL-3.0-only
; Copyright (c) 2026 Cryosphere Innovation
; (a wholly owned subsidiary of JASCO Applied Sciences).
;
; Contact: Dr. Cameron Planck <cjp@cryosphereinnovation.com>
;
; PlatformIO project configuration for the OpenString firmware.
; Docs: https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware/src

[env:adafruit_feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
monitor_speed = 115200
lib_deps =
    paulstoffregen/OneWire@^2.3.8
